name: Build Pipeline

on:
  push:
    branches:
      - 'KAN-1-add-ai-chat-bot'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Display Build Message
        run: echo "GitHub Actions Build Successful"
